DELETE FROM AUTHORITY;

INSERT INTO AUTHORITY (AUTHORITY_ID, AUTHORITY_DESC) VALUES ('VIEW','Very Basic Authority, all user should have it');

DELETE FROM ROLE_INFO;

INSERT INTO ROLE_INFO (ROLE_ID,ROLE_DISPLAY_NM) VALUES ('VIEWER','Basic Role to access app');

DELETE FROM ROLE_AUTHORITY;

INSERT INTO ROLE_AUTHORITY (ROLE_ID,AUTHORITY_ID) VALUES ('VIEWER','VIEW');
