DROP TABLE IF EXISTS LOGIN_INFO;
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS ROLE_AUTHORITY;
DROP TABLE IF EXISTS AUTHORITY;
DROP TABLE IF EXISTS ROLE_INFO;
DROP TABLE IF EXISTS USER_DETAILS;


CREATE TABLE IF NOT EXISTS USER_DETAILS (
	USER_ID VARCHAR(100),
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	EMAIL_ADDRESS VARCHAR(100),
	PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS LOGIN_INFO  (
	ID BIGINT IDENTITY,
	USER_ID VARCHAR(100),
	PASSWORD VARCHAR(100),
	LAST_LOGGED TIMESTAMP,
	FOREIGN KEY(USER_ID) REFERENCES USER_DETAILS(USER_ID)
);

CREATE TABLE IF NOT EXISTS ROLE_INFO(
	ROLE_ID VARCHAR(100),
	ROLE_DISPLAY_NM VARCHAR(100),
	PRIMARY KEY(ROLE_ID)
);

CREATE TABLE IF NOT EXISTS USER_ROLE(
	ID BIGINT IDENTITY,
	USER_ID VARCHAR(100),
	ROLE_ID VARCHAR(100),
	FOREIGN KEY(USER_ID) REFERENCES USER_DETAILS(USER_ID),
	FOREIGN KEY(ROLE_ID) REFERENCES ROLE_INFO(ROLE_ID)
);

CREATE TABLE IF NOT EXISTS AUTHORITY(
	AUTHORITY_ID VARCHAR(100),
	AUTHORITY_DESC VARCHAR(1000),
	PRIMARY KEY(AUTHORITY_ID)
);

CREATE TABLE IF NOT EXISTS ROLE_AUTHORITY(
	ROLE_ID VARCHAR(100),
	AUTHORITY_ID VARCHAR(100),
	FOREIGN KEY(AUTHORITY_ID) REFERENCES AUTHORITY(AUTHORITY_ID),
	FOREIGN KEY(ROLE_ID) REFERENCES ROLE_INFO(ROLE_ID)
)